### ISSUE TITLE
Can't run the 'Getting Started' example

### ISSUE THREAD

**Issue by xerosugar** [luboslenco/lue#10]
When building for HTML5, I'm only presented a page that says 'Directory listing for /build/html5/' with a list of files on it...

Also, when I compiled it for Windows, the build/windows folder got a bunch of files in it, but no runnable ones - how do I run the application?

**Comment by luboslenco** [comment]
Hello,

'index.html' should be automatically selected, what browser are you running?

For Windows it creates a Visual Studio project so you can set it up how you need to package application. However I will try to implement 'Play' button, which will automatically build and run native binary. Play button only works on HTML5 and OSX currently.

**Comment by xerosugar** [comment]
I'm using Chrome.

The index.html file should be in build/html5, I assume? There's no html-file in that folder unfortunately... these are the files I have there:
ammo.js
billboard.frag.essl
billboard.vert.essl
data.json
default.frag.essl
default.vert.essl
mesh.frag.essl
mesh.vert.essl
particles.frag.essl
particles.vert.essl
project.kha
Scene.json
shadowmap.frag.essl
shadowmap.vert.essl
skinnedmesh.frag.essl
skinnedmesh.vert.essl

I also do not get a VS-project when I build for windows; in build/windows I have;
data.json
project.kha
Scene.json

**Comment by luboslenco** [comment]
Sorry for late reply - if index.html is missing then error occurred during compilation - can you press 'window' - 'toggle system console' and paste it's contents?

Proper error reporting needs to implemented, will try to figure something out.

**Comment by xerosugar** [comment]
```PyContext 'window' not found
PyContext 'window' not found
Info: Building, see console...

Read new prefs: C:\Users\username\AppData\Roaming\Blender Foundation\Blender\2.
74\config\userpref.blend
found bundled python: C:\Program Files\Blender Foundation\Blender\2.74\python
read blend: C:\Users\username\Desktop\my_project\my_project.blend
Generating Kha project.
Exporting asset 1 of 2 (data.json).
Exporting asset 2 of 2 (Scene.json).
Assets done.

C:\Users\username\Desktop\my_project\Kha\Tools\khamake\Html5Exporter.js:48
                if (path.isAbsolute(this.sources[i])) {
                         ^
TypeError: Object #<Object> has no method 'isAbsolute'
    at Exporter.Html5Exporter.exportSolution (C:\Users\username\Desktop\my_proj
ect\Kha\Tools\khamake\Html5Exporter.js:48:12)
    at exportProjectFiles (C:\Users\username\Desktop\my_project\Kha\Tools\khama
ke\main.js:251:41)
    at C:\Users\username\Desktop\my_project\Kha\Tools\khamake\main.js:549:5
    at Exporter.Html5Exporter.copyBlob (C:\Users\username\Desktop\my_project\Kh
a\Tools\khamake\Html5Exporter.js:145:2)
    at C:\Users\username\Desktop\my_project\Kha\Tools\khamake\main.js:547:13
    at exportAssets (C:\Users\username\Desktop\my_project\Kha\Tools\khamake\mai
n.js:173:3)
    at C:\Users\username\Desktop\my_project\Kha\Tools\khamake\main.js:231:4
    at Exporter.Html5Exporter.copyBlob (C:\Users\username\Desktop\my_project\Kh
a\Tools\khamake\Html5Exporter.js:145:2)
    at exportAssets (C:\Users\username\Desktop\my_project\Kha\Tools\khamake\mai
n.js:230:12)
    at C:\Users\username\Desktop\my_project\Kha\Tools\khamake\main.js:231:4
Build done!

Blender quit
127.0.0.1 - - [18/May/2015 16:35:06] "GET /build/html5 HTTP/1.1" 301 -
127.0.0.1 - - [18/May/2015 16:35:06] "GET /build/html5/ HTTP/1.1" 200 -
127.0.0.1 - - [18/May/2015 16:35:07] code 404, message File not found
127.0.0.1 - - [18/May/2015 16:35:07] "GET /favicon.ico HTTP/1.1" 404 -
```

**Comment by luboslenco** [comment]
Looks like node.js is outdated:)

**Comment by xerosugar** [comment]
what really? which line tells you that? :p

**Comment by xerosugar** [comment]
I upgraded Node. Now I get an alert telling me "loadBlob failed". Let me know if you want to see the log again.

**Comment by luboslenco** [comment]
Good idea, wIll definitely add minimal versions of stuff in the docs.

Log would be helpful. Thanks for patience - this will help a lot to improve getting starting process:)

**Comment by xerosugar** [comment]
No problem :)

Here's the log:
```
Read new prefs: C:\Users\username\AppData\Roaming\Blender Foundation\Blender\2.
74\config\userpref.blend
found bundled python: C:\Program Files\Blender Foundation\Blender\2.74\python
read blend: C:\Users\username\Desktop\my_project\my_project.blend
Read new prefs: C:\Users\username\AppData\Roaming\Blender Foundation\Blender\2.
74\config\userpref.blend
found bundled python: C:\Program Files\Blender Foundation\Blender\2.74\python
read blend: C:\Users\username\Desktop\my_project\my_project.blend
PyContext 'window' not found
PyContext 'window' not found
Info: Building, see console...

Read new prefs: C:\Users\username\AppData\Roaming\Blender Foundation\Blender\2.
74\config\userpref.blend
found bundled python: C:\Program Files\Blender Foundation\Blender\2.74\python
read blend: C:\Users\username\Desktop\my_project\my_project.blend
Generating Kha project.
Exporting asset 1 of 2 (data.json).
Exporting asset 2 of 2 (Scene.json).
Assets done.
Shader compiler process exited with code 3221225781
Shader compiler process exited with code 3221225781
Shader compiler process exited with code 3221225781
Shader compiler process exited with code 3221225781
Shader compiler process exited with code 3221225781
Shader compiler process exited with code 3221225781
Shader compiler process exited with code 3221225781
Shader compiler process exited with code 3221225781
Shader compiler process exited with code 3221225781
Shader compiler process exited with code 3221225781
Done.
Build done!

Blender quit
127.0.0.1 - - [19/May/2015 19:30:56] "GET /build/html5/ HTTP/1.1" 200 -
127.0.0.1 - - [19/May/2015 19:30:56] "GET /build/html5/kha.js HTTP/1.1" 200 -
127.0.0.1 - - [19/May/2015 19:30:56] "GET /build/html5/ammo.js HTTP/1.1" 200 -
127.0.0.1 - - [19/May/2015 19:30:56] "GET /build/html5/project.kha HTTP/1.1" 200
 -
127.0.0.1 - - [19/May/2015 19:30:57] code 404, message File not found
127.0.0.1 - - [19/May/2015 19:30:57] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [19/May/2015 19:30:57] code 404, message File not found
127.0.0.1 - - [19/May/2015 19:30:57] "GET /build/html5/painter-colored.frag.essl
 HTTP/1.1" 404 -
127.0.0.1 - - [19/May/2015 19:30:57] code 404, message File not found
127.0.0.1 - - [19/May/2015 19:30:57] "GET /build/html5/painter-colored.vert.essl
 HTTP/1.1" 404 -
127.0.0.1 - - [19/May/2015 19:30:57] code 404, message File not found
127.0.0.1 - - [19/May/2015 19:30:57] "GET /build/html5/painter-image.frag.essl H
TTP/1.1" 404 -
127.0.0.1 - - [19/May/2015 19:30:57] code 404, message File not found
127.0.0.1 - - [19/May/2015 19:30:57] "GET /build/html5/painter-image.vert.essl H
TTP/1.1" 404 -
127.0.0.1 - - [19/May/2015 19:30:57] code 404, message File not found
127.0.0.1 - - [19/May/2015 19:30:57] "GET /build/html5/painter-text.frag.essl HT
TP/1.1" 404 -
127.0.0.1 - - [19/May/2015 19:30:57] code 404, message File not found
127.0.0.1 - - [19/May/2015 19:30:57] "GET /build/html5/painter-text.vert.essl HT
TP/1.1" 404 -
127.0.0.1 - - [19/May/2015 19:30:57] code 404, message File not found
127.0.0.1 - - [19/May/2015 19:30:57] "GET /build/html5/painter-video.frag.essl H
TTP/1.1" 404 -
127.0.0.1 - - [19/May/2015 19:30:57] code 404, message File not found
127.0.0.1 - - [19/May/2015 19:30:57] "GET /build/html5/painter-video.vert.essl H
TTP/1.1" 404 -
127.0.0.1 - - [19/May/2015 19:30:57] code 404, message File not found
127.0.0.1 - - [19/May/2015 19:30:57] "GET /build/html5/scene-mesh.frag.essl HTTP
/1.1" 404 -
127.0.0.1 - - [19/May/2015 19:30:57] code 404, message File not found
127.0.0.1 - - [19/May/2015 19:30:57] "GET /build/html5/scene-mesh.vert.essl HTTP
/1.1" 404 -
127.0.0.1 - - [19/May/2015 19:30:57] "GET /build/html5/billboard.frag.essl HTTP/
1.1" 200 -
127.0.0.1 - - [19/May/2015 19:30:57] "GET /build/html5/billboard.vert.essl HTTP/
1.1" 200 -
127.0.0.1 - - [19/May/2015 19:30:57] "GET /build/html5/default.frag.essl HTTP/1.
1" 200 -
127.0.0.1 - - [19/May/2015 19:30:57] "GET /build/html5/default.vert.essl HTTP/1.
1" 200 -
127.0.0.1 - - [19/May/2015 19:30:57] "GET /build/html5/mesh.frag.essl HTTP/1.1"
200 -
127.0.0.1 - - [19/May/2015 19:30:57] "GET /build/html5/mesh.vert.essl HTTP/1.1"
200 -
127.0.0.1 - - [19/May/2015 19:30:57] "GET /build/html5/particles.frag.essl HTTP/
1.1" 200 -
127.0.0.1 - - [19/May/2015 19:30:57] "GET /build/html5/particles.vert.essl HTTP/
1.1" 200 -
127.0.0.1 - - [19/May/2015 19:30:57] "GET /build/html5/shadowmap.frag.essl HTTP/
1.1" 200 -
127.0.0.1 - - [19/May/2015 19:30:57] "GET /build/html5/shadowmap.vert.essl HTTP/
1.1" 200 -
127.0.0.1 - - [19/May/2015 19:30:57] "GET /build/html5/skinnedmesh.frag.essl HTT
P/1.1" 200 -
127.0.0.1 - - [19/May/2015 19:30:57] "GET /build/html5/skinnedmesh.vert.essl HTT
P/1.1" 200 -
```

**Comment by krupin-maxim** [comment]
I built project in terminal by "node Kha/make.js html5" command and all this files *.essl generated. But I have others problems. File "ammo.js" was missed, so I copy/pasted it manual. Finally, my browser started the app, but nothing showed, because

kha.js:10485 Uncaught Error: Could not compile shader:
ERROR: 0:24: '_33' : undeclared identifier 
ERROR: 0:26: '_43' : undeclared identifier 
ERROR: 0:26: 'assign' :  cannot convert from 'float' to 'varying mediump 3-component vector of float'
ERROR: 0:29: '_61' : undeclared identifier 
ERROR: 0:29: 'assign' :  cannot convert from 'float' to 'varying mediump 3-component vector of float'

**Comment by luboslenco** [comment]
Hey,

You need to build project from Blender, which copies ammo.js automatically and exports all necessary scene data. Once this is done and you only change source code, then it can be compiled also from command line. Or did it not work from Blender anyway?

Everything should be getting stable again these days, works on OSX but need to check others. I really need to streamline the getting started process, as there seems to be a lot of issues coming up.

**Comment by krupin-maxim** [comment]
Now it works from Blender, but I cannot understand why it didn't work before. First zblend run is very hard, if internet connection is slow - git clonning Kha project lose in Blender. 

So, I have ubuntu 14.04 and there kha.js errors in any browser (firefox, chrome, chromium). 

Also, it is very stupid to generate project solution for flash in FlashDevelop instead generating swf-file. FlashDevelop is windows IDE only (I use Jetbrains IDEA). Can you help, which command can build swf -file by haxe in terminal?

**Comment by luboslenco** [comment]
Definitely need to provide some UI feedback for cloning dependencies, but it is not as straightforward to do in Blender. You can look in console for now, but that is not ideal solution. Will try to figure something out.

Kha always creates a FlashDevelop project in build directory for some reason. ZBlend does not support Flash target though - stage3D was too limited in regards to register and instruction count for shaders.

**Comment by luboslenco** [comment]
Spring cleaning - will provide a proper getting started guide.
